apiVersion: v1
kind: Service
metadata:
  name: django-argo-service
  namespace: django-argo
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30007
